[app]

#
# MichaelTV — Android port of MichaelTVPlayer.
#
# BEFORE building, sync the shared core from ../src into ./michaeltv_core/
# and re-stamp the version lines below:
#
#     python android/prepare_core.py
#
# (run from the repo root; it rewrites `version =` and
# `android.numeric_version =` from src/config.py's APP_VERSION)
#

# Application title in the launcher.
title = MichaelTV

# Package name — combined with package.domain this yields the Android
# package id org.michaeltv.michaeltv.
package.name = michaeltv
package.domain = org.michaeltv

# Everything in this directory (main.py, mv/, michaeltv_core/, icon.png)
# is bundled. michaeltv_core/ is generated by prepare_core.py and is NOT
# in git — always run it first or the APK will crash on import.
source.dir = .

source.include_exts = py,png,jpg,kv,atlas,json

# Version string. MANAGED BY prepare_core.py (from src/config.py's
# APP_VERSION) — do not bump by hand, bump src/config.py instead and
# re-run:  python android/prepare_core.py
version = 2.1

# Kivy UI + ffpyplayer (the Video widget's backend), android/pyjnius for
# keep-screen-on and friends, requests for the shared stremio/xtream core.
requirements = python3,kivy==2.3.0,android,pyjnius,requests,ffpyplayer

# Landscape and portrait; the layouts are orientation-agnostic.
# (buildozer 1.5.0 rejects "all" — a comma list is the accepted form.)
orientation = portrait,landscape

# Fullscreen when the status bar would overlay video, normal otherwise.
fullscreen = auto

# Copied from ../assets/icon.png (1024x1024 RGBA master).
icon.filename = %(source.dir)s/icon.png

#
# Android specific
#

# The only permission the app needs — every stream/Cinemeta/Xtream call
# is plain HTTPS/HTTP.
android.permissions = INTERNET

# Target / minimum Android levels (Android 14 target, 7.0 floor).
android.api = 34
android.minapi = 24
android.ndk = 25b

# Integer build code. MANAGED BY prepare_core.py (digits of the version
# with dots stripped: "2.1" -> 21) — bump src/config.py and re-run it.
android.numeric_version = 21

# 64-bit only — every current device is arm64 and it halves the APK.
android.archs = arm64-v8a

# Accept the SDK licences non-interactively in CI.
android.accept_sdk_license = True

# python-for-android checkout to build with. The GitHub Actions workflow
# sed-replaces the placeholder with its pinned p4a clone before running
# buildozer, e.g.:
#     sed -i "s|P4A_SOURCE_DIR_PLACEHOLDER|/opt/python-for-android|g" \
#         android/buildozer.spec
# For a LOCAL build either point this at your own python-for-android
# checkout, or comment the line out and set p4a.branch below instead.
p4a.source_dir = P4A_SOURCE_DIR_PLACEHOLDER

# Only relevant when p4a.source_dir above is commented out — pins the
# p4a branch buildozer clones for itself:
# p4a.branch = master

# (Optional) APK metadata:
# android.presplash_time = 2
# android.allow_backup = False

#
# Control logging behavior (log_level 2 = INFO, useful for first builds)
#

[buildozer]
log_level = 2
warn_on_root = 1

#
# List the sections in which you are using the hooks
#

# post_build = ./post_build.py
